#!/usr/bin/env python3
"""Convert design/retro-sap-gui/icons.svg (16x16 pixel sprite) into a WPF
ResourceDictionary of DrawingImages: src/RetroCap/Theme/Icons.xaml.

Each <symbol id="name"> becomes <DrawingImage x:Key="Icon.name">.
Run from the repo root:  python3 tools/gen_icons.py
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "design/retro-sap-gui/icons.svg"
DST = ROOT / "src/RetroCap/Theme/Icons.xaml"
NS = "{http://www.w3.org/2000/svg}"

# Class palette, kept in sync with the <style> block in icons.svg.
CLASS_FILL = {
    "doc-line": "#000000", "doc-fill": "#FFFFFF", "doc-fold": "#A6B4C5",
    "white": "#FFFFFF", "gray": "#A6B4C5", "blue": "#2A6FB8", "blue-d": "#003D7A",
    "green": "#2E8B3E", "red": "#C8281E", "yellow": "#F0AB00",
}


def esc(s):
    return s.replace("&", "&amp;").replace("\"", "&quot;")


def fill_of(el):
    f = el.get("fill")
    if f is None and el.get("class"):
        f = CLASS_FILL.get(el.get("class"))
    if f in (None, "none"):
        return None
    return f


def pen_of(el):
    st = el.get("stroke")
    if not st or st == "none":
        return ""
    w = el.get("stroke-width", "1")
    return f'<GeometryDrawing.Pen><Pen Brush="{st}" Thickness="{w}" LineJoin="Miter"/></GeometryDrawing.Pen>'


def drawing(geom, el, force_fill=None):
    f = force_fill or fill_of(el)
    pen = pen_of(el)
    if not f and not pen:
        return ""
    brush = f' Brush="{f}"' if f else ""
    return f'<GeometryDrawing{brush} Geometry="{esc(geom)}">{pen}</GeometryDrawing>' if pen else \
        f'<GeometryDrawing{brush} Geometry="{esc(geom)}"/>'


def points_geom(pts):
    nums = re.split(r"[\s,]+", pts.strip())
    pairs = [f"{nums[i]},{nums[i+1]}" for i in range(0, len(nums), 2)]
    return "M" + pairs[0] + " L" + " ".join(pairs[1:]) + " Z"


def transform_of(t):
    if not t:
        return None
    m = [1, 0, 0, 1, 0, 0]

    def mul(a, b):
        return [a[0]*b[0] + a[2]*b[1], a[1]*b[0] + a[3]*b[1],
                a[0]*b[2] + a[2]*b[3], a[1]*b[2] + a[3]*b[3],
                a[0]*b[4] + a[2]*b[5] + a[4], a[1]*b[4] + a[3]*b[5] + a[5]]
    for name, args in re.findall(r"(\w+)\(([^)]*)\)", t):
        v = [float(x) for x in re.split(r"[\s,]+", args.strip())]
        if name == "translate":
            m = mul(m, [1, 0, 0, 1, v[0], v[1] if len(v) > 1 else 0])
        elif name == "scale":
            m = mul(m, [v[0], 0, 0, v[1] if len(v) > 1 else v[0], 0, 0])
    return ",".join(f"{x:g}" for x in m)


def convert(el, symbols):
    tag = el.tag.replace(NS, "")
    if tag == "rect":
        x, y, w, h = (el.get(k, "0") for k in ("x", "y", "width", "height"))
        return drawing(f"M{x},{y} h{w} v{h} h-{w} Z", el)
    if tag == "polygon":
        return drawing(points_geom(el.get("points")), el)
    if tag == "path":
        d = el.get("d")
        if el.get("fill-rule") == "evenodd":
            d = "F0 " + d
        return drawing(d, el)
    if tag in ("circle", "ellipse"):
        cx, cy = el.get("cx"), el.get("cy")
        rx = el.get("rx", el.get("r"))
        ry = el.get("ry", el.get("r"))
        geom = f"M{float(cx)-float(rx):g},{cy} A{rx},{ry} 0 1 1 {float(cx)+float(rx):g},{cy} A{rx},{ry} 0 1 1 {float(cx)-float(rx):g},{cy} Z"
        return drawing(geom, el)
    if tag == "line":
        return drawing(f"M{el.get('x1')},{el.get('y1')} L{el.get('x2')},{el.get('y2')}", el)
    if tag == "use":
        ref = (el.get("href") or el.get("{http://www.w3.org/1999/xlink}href")).lstrip("#")
        return "".join(convert(c, symbols) for c in symbols[ref])
    if tag == "g":
        inner = "".join(convert(c, symbols) for c in el)
        tr = transform_of(el.get("transform"))
        if tr:
            return f'<DrawingGroup Transform="{tr}">{inner}</DrawingGroup>'
        return f"<DrawingGroup>{inner}</DrawingGroup>"
    # <text> and anything else: not representable as pixel geometry; skipped.
    return ""


def main():
    tree = ET.parse(SRC)
    symbols = {s.get("id"): list(s) for s in tree.getroot().iter(NS + "symbol")}
    out = ['<!-- GENERATED by tools/gen_icons.py from design/retro-sap-gui/icons.svg. Do not edit. -->',
           '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
           '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">']
    for name, children in symbols.items():
        body = "".join(convert(c, symbols) for c in children)
        # Transparent 16x16 frame keeps every icon's bounds identical.
        frame = '<GeometryDrawing Brush="Transparent" Geometry="M0,0 h16 v16 h-16 Z"/>'
        out.append(f'  <DrawingImage x:Key="Icon.{name}"><DrawingImage.Drawing>'
                   f'<DrawingGroup ClipGeometry="M0,0 h16 v16 h-16 Z">{frame}{body}</DrawingGroup>'
                   f'</DrawingImage.Drawing></DrawingImage>')
    out.append("</ResourceDictionary>")
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(symbols)} icons to {DST.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
